### ISSUE TITLE
Callback when TreeNode build has completed?

### ISSUE THREAD

**Issue by Uche01** [baumths/flutter_tree_view#94]
I just implemented a code that measures the size of each nodes and scrolls to the node on node selection. This works well when a node is selected and widget doesn't rebuild, however when widget is rebuilt, I'd have to call the `scrollToNode` function manually which still doesn't work.

I am calling the scrollToNode() function inside `WidgetsBinding.instance.addPostFrameCallback((_) {})` function. 

eg This does not work:
```
WidgetsBinding.instance.addPostFrameCallback((_) {
   scrollToNode()
});
```

But works after I set a delay:
```
WidgetsBinding.instance.addPostFrameCallback((_) {
   Timer(Duration(milliseconds: 100), () {
        scrollToNode();
      });
});
```
My guess is that TreeNode build is yet to complete before `WidgetsBinding.instance.addPostFrameCallback((_) {})` is called. 

**Now to my question:** 
Are there some mechanism or function I could use to detect that TreeNode has completed?

**Comment by baumths** [comment]
Not that I can think of, yet.

I was planning on adding a `onTreeRebuilt` callback that would be called each time the tree views finished flattening the tree. Not sure when I will get to it tho.

**Comment by baumths** [comment]
I've added the `onTreeChanged` callback to the [dev/tree-changed-callback](https://github.com/baumths/flutter_tree_view/tree/dev/tree-changed-callback) branch.

Could you check it out and tell me if is solves your problem? If so, I will push it to pub.dev as soon as possible.

To try it out on your project, add the following lines to your `pubspec.yaml`:
```yaml
dependency_overrides:
  flutter_fancy_tree_view:
    git:
      url: https://github.com/baumths/flutter_tree_view.git
      ref: dev/tree-changed-callback
```

**Comment by baumths** [comment]
I've added the `onTreeChanged` callback to the [dev/tree-changed-callback](https://github.com/baumths/flutter_tree_view/tree/dev/tree-changed-callback) branch.

Could you check it out and tell me if is solves your problem? If so, I will push it to pub.dev as soon as possible.

To try it out on your project, add the following lines to your `pubspec.yaml`:
```yaml
dependency_overrides:
  flutter_fancy_tree_view:
    git:
      url: https://github.com/baumths/flutter_tree_view.git
      ref: dev/tree-changed-callback
```
